config/routes.rb
Rails.application.routes.draw do
  resources :matches 
  resources :players
  resources :teams
  resources :events
  resources :championships
  devise_for :users, controllers:{
  	 omniauth_callbacks: "users/omniauth_callbacks"
  }

  scope "/admin" do
    resources :users
  end
  post "/custom_sign_up", to: "users/omniauth_callbacks#custom_sign_up"


  authenticated :user do
  	root 'main#home'
  end




  unauthenticated :user do
  	root 'main#unregistered'
  end

  
  get  'matches-create' => 'matches#generate_form'
  post 'matches-generate' => 'matches#generate'
  
  get  'details_match/:match_id/new'    => 'details_matches#new_detail'
  post 'details_match/:match_id/create' => 'details_matches#create_detail'
  get  'matches/:match_id/close' => 'matches#close'
  get  'search-players' => 'players#search'
  get  'staticstics/table-positions' => 'staticstics#table_positions'
  get  'staticstics/table-events' => 'staticstics#table_players_goals'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/championship.rb
class Championship < ApplicationRecord
	has_many :matches
	has_many :championships
  def getMatches
      matches = Match.where(Championship_id:id).count;
      return matches
  end
end

app/controllers/championships_controller.rb
class ChampionshipsController < ApplicationController
  before_action :set_championship, only: [:show, :edit, :update, :destroy]

  # GET /championships
  # GET /championships.json
  def index
    @championships = Championship.all
  end

  # GET /championships/1
  # GET /championships/1.json
  def show
    @days = { 1 => "Lunes",
                2 => "Martes",
                3 => "Miercoles",
                4 => "Jueves",
                5 => "Viernes",
                6 => "Sabado",
                7 => "Domingo",
         }
  end

  # GET /championships/new
  def new
    @championship = Championship.new
    @days = { 1 => "Lunes",
                2 => "Martes",
                3 => "Miercoles",
                4 => "Jueves",
                5 => "Viernes",
                6 => "Sabado",
                7 => "Domingo",
         }
  end

  # GET /championships/1/edit
  def edit
    @days = { 1 => "Lunes",
                2 => "Martes",
                3 => "Miercoles",
                4 => "Jueves",
                5 => "Viernes",
                6 => "Sabado",
                7 => "Domingo",
         }
  end

  # POST /championships
  # POST /championships.json
  def create
    set_days_game
    @championship = Championship.new(championship_params)
    respond_to do |format|
      if @championship.save
        format.html { redirect_to '/championships', notice: 'Campeonato creado correctamente.' }
        format.json { render :show, status: :created, location: @championship }
      else
        format.html { render :new }
        format.json { render json: @championship.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /championships/1
  # PATCH/PUT /championships/1.json
  def update
    respond_to do |format|
    set_days_game
    puts params
      if @championship.update(championship_params)
        format.html { redirect_to @championship, notice: 'Campeonato actulizado correctamente.' }
        format.json { render :show, status: :ok, location: @championship }
      else
        format.html { render :edit }
        format.json { render json: @championship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /championships/1
  # DELETE /championships/1.json
  def destroy
    @championship.destroy
    respond_to do |format|
      format.html { redirect_to championships_url, notice: 'Championship was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_championship
      @championship = Championship.find(params[:id])
    end
    def set_days_game
      params[:championship][:game_days] = params[:days].join(',')
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def championship_params
      params.require(:championship).permit(:name, :quantity_min_teams, :date_initial_inscription, :date_end_inscription, :match_duration, :matches_simultanius, :game_days)
    end
end

app/helpers/championships_helper.rb
module ChampionshipsHelper
end

app/views/championships/_form.html.haml
= form_for @championship do |f|
  - if @championship.errors.any?
    #error_explanation
      %h3= "#{pluralize(@championship.errors.count, "error")} prohibited this championship from being saved:"
      %ul
        - @championship.errors.full_messages.each do |msg|
          %li= msg
  .form-group.row 
    = f.label "Nombre:",class:"col-sm-3 col-md-2 col-form-label"
    .col-sm-6.col-xs-12.col-md-4
      = f.text_field :name,class:"form-control"
  .form-group.row
    = f.label "Cantidad minima de equipos",class:"col-sm-3 col-md-2 col-form-label"
    .col-sm-6.col-xs-12.col-md-4
      = f.number_field :quantity_min_teams,class:"form-control"
  .form-group.row
    = f.label "Fecha inicio inscripción",class:"col-sm-3 col-md-2 col-form-label"
    .col-sm-6.col-xs-12.col-md-4
      = f.text_field :date_initial_inscription,class:"form-control"
  .form-group.row
    = f.label "Fecha fin inscripción",class:"col-sm-3 col-md-2 col-form-label"
    .col-sm-6.col-xs-12.col-md-4
      = f.text_field :date_end_inscription,class:"form-control"
  .form-group.row
    = f.label "Duración partido",class:"col-sm-3 col-md-2 col-form-label"
    .col-sm-6.col-xs-12.col-md-4
      = f.text_field :match_duration,class:"form-control"
  .form-group.row
    = f.label "Cant. Partidos simultaneos",class:"col-sm-3 col-md-2 col-form-label"
    .col-sm-6.col-xs-12.col-md-4
      = f.text_field :matches_simultanius,class:"form-control"
  .form-group.row
    = f.label "Dias de juego",class:"col-sm-3 col-md-2 col-form-label"
    .col-sm-6.col-xs-12.col-md-4
      - @days.each do |key,day|
        = day      
        = check_box_tag "days[]", key, @championship.game_days.present? && @championship.game_days.include?(key.to_s)

  .form-group.row
    .offset-md-2.col-md-4
      %button.btn.btn-success{"type"=>"submit"}
        %i.fa.fa-floppy-o{"aria-hidden"=>"true"}
        %span  Guardar
      %a.btn.btn-secondary{"href"=>"/championships"} <i class="fa fa-arrow-circle-left" aria-hidden="true"></i> Atras   
      

app/views/championships/edit.html.haml
.col-xs-12.white
  %h2 Editar campeonato
  = render 'form'

app/views/championships/index.html.haml
.col-xs-12.col-sm-12.col-md-12.col-lg-12{"style"=>"background: white;"}
  .big-padding
    .big-padding{"style"=>"border:solid #f7f7f9;"}
      %h1 Championships
      %table.table.table-striped
        %thead
          %tr
            %th #
            %th Nombre
            %th.hidden-sm-down Cant min. Equip.
            %th.hidden-sm-down Fec Ini. Inscripción
            %th.hidden-sm-down Fec. Fin. Inscripción
            %th
        %tbody
          - @championships.each do |championship|
            %tr
              %td= championship.id
              %td= championship.name
              %td.hidden-sm-down= championship.quantity_min_teams
              %td.hidden-sm-down= championship.date_initial_inscription
              %td.hidden-sm-down= championship.date_end_inscription
              %td
                .dropdown
                  %button.btn.btn-secondary.dropdown-toggle{"type"=>"button","id"=>"actions","data-toggle"=>"dropdown","aria-haspopup"=>"true","aria-expanded"=>"false"} Acciones
                  .dropdown-menu{"aria-labelledby"=>"actions"}
                    = link_to 'Ver', championship,:class=>"dropdown-item"
                    = link_to 'Editar', edit_championship_path(championship),:class=>"dropdown-item"
                    %a.dropdown-item{"href"=>"/teams?championship_id=#{championship.id}"} Equipos
                    %a.dropdown-item{"href"=>"/matches?championship_id=#{championship.id}"} Partidos
                    %a.dropdown-item{"href"=>"/matches-create?championship_id=#{championship.id}"} Programación
      %br
      %a.btn.btn-success{"href"=>"/championships/new"} <i class="fa fa-plus" aria-hidden="true"></i> Add

app/views/championships/new.html.haml
.col-xs-12.white
  %h2 Crear campeonato
  = render 'form'
      

app/views/championships/show.html.haml
.col-xs-12.white
  .box       
    .big-padding
      %p#notice= notice
      %table.table
        %thead
          %tr
            %th.text-center{:colspan => 2,style:"text-align:left;"}= @championship.name
        %tbody
          %tr
            %td Cantidad equipos:
            %td= @championship.quantity_min_teams
          %tr
            %td Fecha inicio inscripción:
            %td= @championship.date_initial_inscription
          %tr
            %td Fecha fin inscripción:
            %td= @championship.date_end_inscription
          %tr
            %td Duración partido:
            %td= @championship.match_duration
          %tr
            %td Cantidad partidos simultaneos:
            %td= @championship.matches_simultanius
          %tr
            %td Dias de juego:
            %td
              - @days.each do |key,day|
                - if @championship.game_days.include?(key.to_s)
                  = day

      %br
      = link_to 'Editar', edit_championship_path(@championship),:class=>'btn btn-primary'
      = link_to 'Atras', championships_path,:class=>'btn btn-secondary'